"""The crm pack — generated by scripts/new_pack.py (a consumer app on the
Cortex engine). Discovery/reads/actions go through CortexOS.agent_sdk with
pack="crm"; a real deployment adds a query backend (see CortexOS/agent_sdk/backends.py).
"""
