#!/usr/bin/env pwsh
<#
.SYNOPSIS
  Install (or remove) per-user Cortex engine autostart via Startup folder shortcut.
  Idempotent. Prefer Startup shortcut over Scheduled Task for fewer elevation prompts.

.USAGE
  .\scripts\install_engine_autostart.ps1
  .\scripts\install_engine_autostart.ps1 -Port 8010
  .\scripts\install_engine_autostart.ps1 -DryRun
  .\scripts\install_engine_autostart.ps1 -Uninstall
#>
param(
    [int]$Port = 8010,
    [string]$Pack = "dms",
    [switch]$DryRun,
    [switch]$Uninstall
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$StartBat = Join-Path $Root "START_ENGINE.bat"
$StartPs1 = Join-Path $Root "scripts\start_cortex_engine.ps1"
$DataDir = Join-Path $Root "data\engine"
$LogFile = Join-Path $DataDir "autostart.log"
$StartupDir = Join-Path $env:APPDATA "Microsoft\Windows\Start Menu\Programs\Startup"
$ShortcutPath = Join-Path $StartupDir "CortexEngine.lnk"
$WrapperBat = Join-Path $DataDir "autostart_launch.bat"

New-Item -ItemType Directory -Force -Path $DataDir | Out-Null

if (-not (Test-Path $StartPs1)) {
    Write-Error "Missing $StartPs1"
    exit 1
}

if ($Uninstall) {
    if ($DryRun) {
        Write-Host "[DryRun] Would remove $ShortcutPath and $WrapperBat"
        exit 0
    }
    Remove-Item $ShortcutPath -Force -ErrorAction SilentlyContinue
    Remove-Item $WrapperBat -Force -ErrorAction SilentlyContinue
    Write-Host "Removed Cortex engine autostart shortcut." -ForegroundColor Green
    exit 0
}

$shellExe = "powershell"
if (Get-Command pwsh -ErrorAction SilentlyContinue) { $shellExe = "pwsh" }

$wrapper = @"
@echo off
REM Autogenerated by install_engine_autostart.ps1 — do not hand-edit
cd /d "$Root"
echo [%DATE% %TIME%] launching Cortex engine port=$Port >> "$LogFile"
$shellExe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "$StartPs1" -Port $Port -Pack $Pack >> "$LogFile" 2>&1
"@

if ($DryRun) {
    Write-Host "[DryRun] Would write wrapper: $WrapperBat"
    Write-Host "[DryRun] Would create shortcut: $ShortcutPath -> $WrapperBat"
    Write-Host "[DryRun] Log: $LogFile"
    Write-Host "[DryRun] START_ENGINE.bat present: $(Test-Path $StartBat)"
    exit 0
}

Set-Content -Path $WrapperBat -Value $wrapper -Encoding ascii

$wshell = New-Object -ComObject WScript.Shell
$sc = $wshell.CreateShortcut($ShortcutPath)
$sc.TargetPath = $WrapperBat
$sc.WorkingDirectory = $Root
$sc.WindowStyle = 7
$sc.Description = "Cortex engine autostart (port $Port)"
$sc.Save()

Write-Host "Installed Cortex engine autostart:" -ForegroundColor Green
Write-Host "  Shortcut: $ShortcutPath"
Write-Host "  Wrapper:  $WrapperBat"
Write-Host "  Log:      $LogFile"
Write-Host "  Port:     $Port"
Write-Host "Re-run with -Uninstall to remove."
