"""O7 — new-pack generator (the FDE payoff).

Takes an approved ontology trio (object / link / action types) for a new vertical
and scaffolds a pack shaped like ``packs/dms/``:

    packs/<name>/
      ontology/{object_types,link_types,action_types,functions}.yaml  # the trio, verbatim
      sql/001_<name>_v0.sql        # DDL generated from object_types
      semantic_layer.yaml          # generated from object+link types (NL->SQL parity)
      compliance/<name>_rules_v1.yaml   # stub, per-pack rules
      audit/__init__.py            # REUSES packs/dms/audit/ledger.py (F1 spine, pack-agnostic)
      __init__.py, ontology/__init__.py

This is "companies create the app they want": an FDE (or the O6 builder) hands a
governed trio, and a runnable pack drops out — the same engine, a new consumer.
Root ``scaffold.py`` is a stale one-time bootstrap and is deliberately NOT reused.

    python -m scripts.new_pack --demo crm
    python -m scripts.new_pack --name crm --from-dir path/with/ontology_yamls

See docs/ontology/CORTEX_ONTOLOGY_PLAN.md §5.3 and docs/strategy/CORTEX_FINAL_GOAL.md.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import yaml

from CortexOS.ontology.registry import (
    ROOT,
    load_link_types,
    load_object_types,
)

_NAME_RE = re.compile(r"^[a-z][a-z0-9_]{1,30}$")

# object-type property type -> SQL column type (SQLite/DuckDB-compatible names)
_SQL_TYPE = {
    "string": "TEXT",
    "number": "DOUBLE",
    "integer": "INTEGER",
    "boolean": "BOOLEAN",
    "date": "DATE",
    "datetime": "TIMESTAMP",
}


class PackExistsError(FileExistsError):
    pass


def _packs_root(packs_root: Path | str | None) -> Path:
    return Path(packs_root) if packs_root is not None else ROOT / "packs"


def _ddl(name: str, objects) -> str:
    lines = [
        f"-- Generated by scripts/new_pack.py for pack '{name}'. Regenerate; do not hand-edit.",
        "-- Portable DDL (TEXT/DOUBLE/INTEGER/BOOLEAN/DATE/TIMESTAMP).",
        "",
    ]
    for obj in objects:
        cols = []
        for p in obj.properties:
            sqltype = _SQL_TYPE.get(p.type, "TEXT")
            cols.append(f"    {p.name} {sqltype}")
        cols.append(f"    PRIMARY KEY ({obj.primary_key})")
        body = ",\n".join(cols)
        lines.append(f"CREATE TABLE IF NOT EXISTS {obj.id} (\n{body}\n);\n")
    return "\n".join(lines)


def _semantic_layer(objects, links) -> dict:
    sensitive = sorted(
        {p.name for o in objects for p in o.properties if not p.agent_visible}
    )
    return {
        "glossary": [],
        "joins": [
            {
                "from_table": link.from_object,
                "from_column": link.from_property,
                "to_table": link.to_object,
                "to_column": link.to_property,
            }
            for link in links
        ],
        "sensitive_columns": sensitive,
        "tables": {o.id: {"columns": [p.name for p in o.properties]} for o in objects},
    }


def _compliance_stub(name: str) -> str:
    return (
        f"# {name} compliance rules (stub — generated by scripts/new_pack.py).\n"
        "# Same shape as packs/dms/compliance/*_rules_v1.yaml; add per-action rules here.\n"
        "rules: []\n"
    )


def _audit_init(name: str) -> str:
    return (
        f'"""Audit for the {name} pack — the F1 hash-chained ledger is pack-agnostic,\n'
        "so this REUSES packs/dms/audit/ledger.py rather than copying it.\n"
        '"""\n'
        "from packs.dms.audit.ledger import (  # noqa: F401 — re-export the shared spine\n"
        "    append,\n"
        "    default_db_path,\n"
        "    list_entries,\n"
        "    verify,\n"
        ")\n"
    )


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def scaffold_pack(
    name: str,
    *,
    object_types_yaml: str,
    link_types_yaml: str,
    action_types_yaml: str,
    functions_yaml: str = "functions: []\n",
    packs_root: Path | str | None = None,
    overwrite: bool = False,
) -> Path:
    """Scaffold ``packs/<name>/`` from a governed ontology trio. Returns the pack dir."""
    if not _NAME_RE.match(name):
        raise ValueError(f"pack name {name!r} must be lower_snake, 2-31 chars")
    pack = _packs_root(packs_root) / name
    if pack.exists() and not overwrite:
        raise PackExistsError(f"{pack} already exists (pass overwrite=True to replace)")

    onto = pack / "ontology"
    _write(onto / "object_types.yaml", object_types_yaml)
    _write(onto / "link_types.yaml", link_types_yaml)
    _write(onto / "action_types.yaml", action_types_yaml)
    _write(onto / "functions.yaml", functions_yaml)
    _write(onto / "__init__.py", f'"""Ontology YAML for the {name} pack (read by CortexOS.ontology)."""\n')

    # Parse back through the shared registry loaders so generated files derive
    # from the exact same objects the engine will load (no drift).
    objects = load_object_types(pack)
    links = load_link_types(pack)

    _write(pack / "sql" / f"001_{name}_v0.sql", _ddl(name, objects))
    _write(
        pack / "semantic_layer.yaml",
        yaml.safe_dump(_semantic_layer(objects, links), sort_keys=False, allow_unicode=True),
    )
    _write(pack / "compliance" / f"{name}_rules_v1.yaml", _compliance_stub(name))
    _write(pack / "audit" / "__init__.py", _audit_init(name))
    _write(
        pack / "__init__.py",
        f'"""The {name} pack — generated by scripts/new_pack.py (a consumer app on the\n'
        "Cortex engine). Discovery/reads/actions go through CortexOS.agent_sdk with\n"
        f'pack="{name}"; a real deployment adds a query backend (see CortexOS/agent_sdk/backends.py).\n'
        '"""\n',
    )
    return pack


# --- built-in CRM demo trio (Salesforce UDD shape, PALANTIR_AIP_RESEARCH.md §5) ---

_CRM_OBJECTS = """object_types:
  - id: account
    description: "A company or organization the business sells to."
    primary_key: account_id
    properties:
      - {name: account_id, type: string, agent_visible: true}
      - {name: account_name, type: string, agent_visible: true}
      - {name: industry, type: string, agent_visible: true}
      - {name: annual_revenue, type: number, agent_visible: true}
      - {name: owner_email, type: string, agent_visible: false}
  - id: contact
    description: "A person associated with an account."
    primary_key: contact_id
    properties:
      - {name: contact_id, type: string, agent_visible: true}
      - {name: account_id, type: string, agent_visible: true}
      - {name: full_name, type: string, agent_visible: true}
      - {name: title, type: string, agent_visible: true}
      - {name: email, type: string, agent_visible: false}
      - {name: phone, type: string, agent_visible: false}
  - id: opportunity
    description: "A potential sale tied to an account."
    primary_key: opportunity_id
    properties:
      - {name: opportunity_id, type: string, agent_visible: true}
      - {name: account_id, type: string, agent_visible: true}
      - {name: opp_name, type: string, agent_visible: true}
      - {name: stage, type: string, agent_visible: true}
      - {name: amount, type: number, agent_visible: true}
      - {name: close_date, type: date, agent_visible: true}
      - {name: probability, type: number, agent_visible: true}
"""

_CRM_LINKS = """link_types:
  - id: contact_account
    from_object: contact
    from_property: account_id
    to_object: account
    to_property: account_id
    cardinality: many_to_one
  - id: opportunity_account
    from_object: opportunity
    from_property: account_id
    to_object: account
    to_property: account_id
    cardinality: many_to_one
"""

_CRM_ACTIONS = """action_types:
  - id: account.created
    kind: event
    description: "A new account was created."
    object_type: account
    ledger_event_type: account.created
  - id: opportunity.stage_changed
    kind: event
    description: "An opportunity moved to a new stage."
    object_type: opportunity
    ledger_event_type: opportunity.stage_changed
  - id: crm.export
    kind: tool
    description: "Export a CRM view (demo tool — no runner handler yet, denies fail-closed)."
    required_role: steward
    ledger_event_type: action.tool_call
    requires_confirm: true
    params: [title]
"""

DEMOS = {"crm": (_CRM_OBJECTS, _CRM_LINKS, _CRM_ACTIONS)}


def scaffold_demo(name: str, *, packs_root: Path | str | None = None, overwrite: bool = False) -> Path:
    objs, links, actions = DEMOS[name]
    return scaffold_pack(
        name,
        object_types_yaml=objs,
        link_types_yaml=links,
        action_types_yaml=actions,
        packs_root=packs_root,
        overwrite=overwrite,
    )


def _read_trio(src: Path) -> dict[str, str]:
    out = {}
    for key in ("object_types", "link_types", "action_types"):
        out[f"{key}_yaml"] = (src / f"{key}.yaml").read_text(encoding="utf-8")
    fpath = src / "functions.yaml"
    if fpath.is_file():
        out["functions_yaml"] = fpath.read_text(encoding="utf-8")
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Scaffold a new Cortex pack from an ontology trio.")
    parser.add_argument("--name", help="pack name (lower_snake)")
    parser.add_argument("--from-dir", help="dir with object_types/link_types/action_types.yaml")
    parser.add_argument("--demo", choices=sorted(DEMOS), help="scaffold a built-in demo pack")
    parser.add_argument("--packs-root", default=None, help="override packs/ root (tests)")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args(argv)

    if args.demo:
        pack = scaffold_demo(args.demo, packs_root=args.packs_root, overwrite=args.overwrite)
    elif args.name and args.from_dir:
        pack = scaffold_pack(
            args.name, packs_root=args.packs_root, overwrite=args.overwrite, **_read_trio(Path(args.from_dir))
        )
    else:
        parser.error("give --demo NAME, or --name NAME --from-dir DIR")
    print(f"scaffolded pack: {pack}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
