-- Generated by scripts/new_pack.py for pack 'crm'. Regenerate; do not hand-edit.
-- Portable DDL (TEXT/DOUBLE/INTEGER/BOOLEAN/DATE/TIMESTAMP).

CREATE TABLE IF NOT EXISTS account (
    account_id TEXT,
    account_name TEXT,
    industry TEXT,
    annual_revenue DOUBLE,
    owner_email TEXT,
    PRIMARY KEY (account_id)
);

CREATE TABLE IF NOT EXISTS contact (
    contact_id TEXT,
    account_id TEXT,
    full_name TEXT,
    title TEXT,
    email TEXT,
    phone TEXT,
    PRIMARY KEY (contact_id)
);

CREATE TABLE IF NOT EXISTS opportunity (
    opportunity_id TEXT,
    account_id TEXT,
    opp_name TEXT,
    stage TEXT,
    amount DOUBLE,
    close_date DATE,
    probability DOUBLE,
    PRIMARY KEY (opportunity_id)
);
